// <auto-generated />
using System;
using Fillinger.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fillinger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220119132441_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fillinger.Models.Ember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Nem")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SzuletesiDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Emberek");
                });

            modelBuilder.Entity("Fillinger.Models.Kapcsolat", b =>
                {
                    b.Property<int?>("AnyjaId")
                        .HasColumnType("int");

                    b.Property<int?>("ApjaId")
                        .HasColumnType("int");

                    b.Property<int>("EmberId")
                        .HasColumnType("int");

                    b.HasIndex("AnyjaId");

                    b.HasIndex("ApjaId");

                    b.HasIndex("EmberId");

                    b.ToTable("Kapcsolatok");
                });

            modelBuilder.Entity("Fillinger.Models.Kapcsolat", b =>
                {
                    b.HasOne("Fillinger.Models.Ember", "Anyja")
                        .WithMany()
                        .HasForeignKey("AnyjaId");

                    b.HasOne("Fillinger.Models.Ember", "Apja")
                        .WithMany()
                        .HasForeignKey("ApjaId");

                    b.HasOne("Fillinger.Models.Ember", "Ember")
                        .WithMany()
                        .HasForeignKey("EmberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anyja");

                    b.Navigation("Apja");

                    b.Navigation("Ember");
                });
#pragma warning restore 612, 618
        }
    }
}
